# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('valets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetAssignment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='valet_assignment', serialize=False, to='bookings.booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('return_lat', models.FloatField(blank=True, null=True)),
                ('return_lng', models.FloatField(blank=True, null=True)),
                ('pickup_valet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assignments', to='valets.valet')),
                ('return_valet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_assignments', to='valets.valet')),
            ],
        ),
    ]
