# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to='garages.garage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='authentication.admin')),
            ],
        ),
    ]
