# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('managers', '0001_initial'),
        ('valets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('VALET_ASSIGNED_FOR_CHECK_IN', 'Valet Assigned For Check In'), ('VALET_PICKED_UP', 'Valet Picked Up'), ('CHECKED_IN', 'Checked In'), ('VALET_ASSIGNED_FOR_CHECK_OUT', 'Valet Assigned For Check Out'), ('CHECKED_OUT', 'Checked Out'), ('VALET_RETURNED', 'Valet Returned')], max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_timelines', to='bookings.booking')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_timelines', to='managers.manager')),
                ('valet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_timelines', to='valets.valet')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='booking_tim_booking_d62d1f_idx')],
            },
        ),
    ]
