# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valet',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('licence_id', models.CharField(default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valets', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'uid')},
            },
        ),
    ]
