# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_hour', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('vehicle_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passcode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('VALET_ASSIGNED_FOR_CHECK_IN', 'Valet Assigned For Check In'), ('VALET_PICKED_UP', 'Valet Picked Up'), ('CHECKED_IN', 'Checked In'), ('VALET_ASSIGNED_FOR_CHECK_OUT', 'Valet Assigned For Check Out'), ('CHECKED_OUT', 'Checked Out'), ('VALET_RETURNED', 'Valet Returned')], default='BOOKED', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customer')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slots.slot')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='bookings_bo_start_t_1c7039_idx')],
            },
        ),
    ]
